# Generated by Django 5.1 on 2024-09-02 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Lifestyle & Personal Development', 'Lifestyle & Personal Development'), ('Tech & Innovation', 'Tech & Innovation'), ('Career & Professional Growth', 'Career & Professional Growth'), ('Finance & Business', 'Finance & Business'), ('Travel & Adventure', 'Travel & Adventure'), ('Health & Fitness', 'Health & Fitness'), ('Food & Cooking', 'Food & Cooking'), ('Arts & Creativity', 'Arts & Creativity'), ('Education & Learning', 'Education & Learning'), ('Parenting & Family', 'Parenting & Family')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
